### ISSUE TITLE
Could images of it be shown, in action how it looks?

### ISSUE THREAD

**Issue by rubyFeedback** [chip/glimmer_dsl_with_active_record#2]
Could images of it be shown, in action how it looks?

Does not need to include many images, say 2-4 or so, just so that people understand how it may
look, e. g. from code -> the web-GUI.

**Comment by chip** [comment]
Yes, that's a good idea. 👍🏻 

This is a WIP... I'm currently working on adding migrations and associated docs. I'll keep this here as a placeholder.

 I'm happy to accept PR's in the meantime.

**Comment by chip** [comment]
I've updated this repo with a detailed tutorial in case anyone is interested in the steps involved in creating this repository. A sample image of the app is also provided, with the details to be handled by the end user. I hope others find this useful.
